#!/bin/bash

prefix_list=$1
version=3.6
ToolBox_folder=/home/meyer-lab/ToolBox_v$version
bin=$ToolBox_folder/bin
denscl=$bin/DensCLxC
prefix="pulled"
#resultsfolder=/home/meyer-lab/SeG/results_toolbox/pulled_results/
folder_pulled=/media/meyer-lab/Elements/Work/Stimulus_Barrage/barrage_v2/H2Bslow/pulled_results_bars_dots_sizes/  	#CHANGE HERE!!!
mainresultsfolder=/media/meyer-lab/Elements/Work/Stimulus_Barrage/barrage_v2/H2Bslow/
if [ ! -d $folder_pulled ]; then mkdir $folder_pulled; fi

nEP=5 																									#CHANGE HERE!!!!!

Rscript pull_clusters.R $ToolBox_folder/scripts/$prefix_list $mainresultsfolder $folder_pulled
$denscl $folder_pulled/"all_centers.dat" $folder_pulled/"all_centers_sd.dat" $folder_pulled/$prefix"_summary.dat" $folder_pulled/$prefix"_KNNrecords.dat" $nEP 1.5 -1 $folder_pulled/$prefix"_thresholds.dat" 

