#!/bin/bash

version=3.6
ToolBox_folder=/home/meyer-lab/ToolBox_v$version
bin=$ToolBox_folder/bin
CONFIG=$ToolBox_folder/CONFIG_LIGHTSHEET_2
denscl=$bin/DensCL
classify=$bin/classify_auto
prefix=$1
niftifolder=/media/meyer-lab/Elements/Work/Stimulus_Barrage/barrage_v2/H2Bslow/
#resultsfolder=/home/meyer-lab/SeG/results_toolbox/$prefix/
resultsfolder=$niftifolder/$prefix/im/im_slice_1/results_toolbox #_sizes_270				#CHANGE HERE
if [ ! -d $resultsfolder ]; then mkdir $resultsfolder; fi
timelogfolder=/media/meyer-lab/Elements/Work/Stimulus_Barrage/barrage_v2/ExpLogs_TomSh/

nii=$niftifolder/$prefix/im/im_slice_1/rim_slice_1.nii
epochfile=$timelogfolder/$prefix"_time.log"
#bash epoch_names $epochfile
nEP=`cat $epochfile | wc -l`
nEP=`echo $nEP/2 | bc`
#echo $nEP
# ----------------------
# CLEANING 

tcl=$bin/TCLsimple
baselinesize=20
mwsize=5

#$tcl $nii $resultsfolder $prefix $baselinesize $mwsize

# -------------------------
# SEGMENTATION

cosi=$bin/cosi
#echo $cosi $resultsfolder/$prefix"_cleaned.nii" $resultsfolder $prefix $CONFIG
#$cosi $resultsfolder/$prefix"_cleaned.nii" $resultsfolder $prefix $CONFIG

# -------------------------
# make output

tshift=90 #CHECK THIS
freq=20


mkout=$bin/mkout
#$mkout $resultsfolder/$prefix.bin $epochfile $tshift $freq $resultsfolder/$prefix"_output.dat"

mkout_raw=$bin/mkout_raw
#$mkout_raw $resultsfolder/$prefix.bin $epochfile $tshift $freq $resultsfolder/$prefix"_output_raw.dat"
$mkout_raw $resultsfolder/$prefix.bin $epochfile $tshift $freq $resultsfolder/$prefix"_output_max.dat"

# -----------------------
# COLLAPSE WD EPOCHS

#echo Rscript remove_epochs_ss_dots.R $prefix $resultsfolder $timelogfolder 	#CHANGE HERE	
Rscript remove_epochs_ss_dots.R $prefix $resultsfolder $timelogfolder 		#CHANGE HERE
collapsedepochfile=$resultsfolder/$prefix"_epochsC.dat"
nEP=`cat $collapsedepochfile | wc -l`

#echo "Number of epochs =" $nEP

#-----------------------
# THRESHOLD CELLS BCL based on random noise model
#thresh was 0.625 for dots and 0.44 for simple

#echo Rscript bcl4_script.R $prefix $resultsfolder 					
Rscript bcl4_script.R $prefix $resultsfolder 						

#----------------------
nEP=5			#CHANGED HERE

#CLUSTERING
#echo $denscl $resultsfolder/$prefix"_outputCTM.dat" $resultsfolder/$prefix"_summary.dat" $resultsfolder/$prefix"_KNNrecords.dat" $nEP .5 -4 $resultsfolder/$prefix"_thresholds.dat"
#$denscl $resultsfolder/$prefix"_outputCTM.dat" $resultsfolder/$prefix"_summary.dat" $resultsfolder/$prefix"_KNNrecords.dat" $nEP .5 -4 $resultsfolder/$prefix"_thresholds.dat"
